var pbl_projs = [
	{
		'title': '',
		'authors': '여주안',
		'project_page': 'courses/2022-fall-pbl.html',
		'id': '여주안',
		'year': 2022,
		'season': 'fall',
		'video_iframe': '<iframe width="820" height="461" src="https://www.youtube.com/embed/tbkBYtW6AVE" title="캡스톤PBL Project 4 - Particle Dynamics 영상" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '이지원',
		'project_page': 'courses/2022-fall-pbl.html',
		'id': '이지원',
		'year': 2022,
		'season': 'fall',
		'video_iframe': '<iframe width="1294" height="728" src="https://www.youtube.com/embed/dK8Ul0YUHYY" title="PBL Project4: Particle Dynamics" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '차다윤',
		'project_page': 'courses/2022-fall-pbl.html',
		'id': '차다윤',
		'year': 2022,
		'season': 'fall',
		'video_iframe': '<iframe width="1294" height="728" src="https://www.youtube.com/embed/cvbZfjECuAs" title="CapstonePBL_Motion Viewer with Limb IK & Particle dynamics" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '장보경',
		'project_page': 'courses/2022-fall-pbl.html',
		'id': '장보경',
		'year': 2022,
		'season': 'fall',
		'video_iframe': '<iframe width="1294" height="728" src="https://www.youtube.com/embed/iOdTLo3LiXo" title="한양대학교 컴퓨터소프트웨어학부 CAPSTONE PBL 프로젝트 영상_장보경" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '정은호',
		'project_page': 'courses/2022-fall-pbl.html',
		'id': '정은호',
		'year': 2022,
		'season': 'fall',
		'video_iframe': '<iframe width="820" height="650" src="https://www.youtube.com/embed/E9DUCX9qlJQ" title="BVH Viewer with Simple Limb IK & Particle Dynamics" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
		'type': 'pbl',
	},

	{
		'title': '',
		'authors': '윤혜원',
		'project_page': 'courses/2021-spring-pbl.html',
		'id': '윤혜원',
		'year': 2021,
		'season': 'spring',
		'video_iframe': '<iframe width="1050" height="591" src="https://www.youtube.com/embed/Vc8FVa_gekw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '사정',
		'project_page': 'courses/2021-spring-pbl.html',
		'id': '사정',
		'year': 2021,
		'season': 'spring',
		'video_iframe': '<iframe width="1050" height="591" src="https://www.youtube.com/embed/KHHc6RjXHXM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '김하경',
		'project_page': 'courses/2021-spring-pbl.html',
		'id': '김하경',
		'year': 2021,
		'season': 'spring',
		'video_iframe': '<iframe width="1050" height="591" src="https://www.youtube.com/embed/2uTez1CI9sA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'pbl',
	},

	{
		'title': '',
		'authors': '백종원',
		'project_page': 'courses/2020-spring-pbl.html',
		'id': '백종원',
		'year': 2020,
		'season': 'spring',
		'video_iframe': '<iframe width="1050" height="591" src="https://www.youtube.com/embed/ohq_Ly1f2GM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '심민호',
		'project_page': 'courses/2020-spring-pbl.html',
		'id': '심민호',
		'year': 2020,
		'season': 'spring',
		'video_iframe': '<iframe width="1050" height="591" src="https://www.youtube.com/embed/jHx-xYuXZ-s" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '정영주',
		'project_page': 'courses/2020-spring-pbl.html',
		'id': '정영주',
		'year': 2020,
		'season': 'spring',
		'video_iframe': '<iframe width="1050" height="591" src="https://www.youtube.com/embed/Q2uoJJT2XZc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'pbl',
	},
]
