var pbl_projs = [
	{
		'title': '',
		'authors': '윤혜원',
		'project_page': 'courses/2021-spring-pbl.html',
		'id': '윤혜원',
		'year': 2021,
		'season': 'spring',
		'video_iframe': '<iframe width="1050" height="591" src="https://www.youtube.com/embed/Vc8FVa_gekw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '사정',
		'project_page': 'courses/2021-spring-pbl.html',
		'id': '사정',
		'year': 2021,
		'season': 'spring',
		'video_iframe': '<iframe width="1050" height="591" src="https://www.youtube.com/embed/KHHc6RjXHXM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '김하경',
		'project_page': 'courses/2021-spring-pbl.html',
		'id': '김하경',
		'year': 2021,
		'season': 'spring',
		'video_iframe': '<iframe width="1050" height="591" src="https://www.youtube.com/embed/2uTez1CI9sA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '백종원',
		'project_page': 'courses/2020-spring-pbl.html',
		'id': '백종원',
		'year': 2020,
		'season': 'spring',
		'video_iframe': '<iframe width="1050" height="591" src="https://www.youtube.com/embed/ohq_Ly1f2GM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '심민호',
		'project_page': 'courses/2020-spring-pbl.html',
		'id': '심민호',
		'year': 2020,
		'season': 'spring',
		'video_iframe': '<iframe width="1050" height="591" src="https://www.youtube.com/embed/jHx-xYuXZ-s" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'pbl',
	},
	{
		'title': '',
		'authors': '정영주',
		'project_page': 'courses/2020-spring-pbl.html',
		'id': '정영주',
		'year': 2020,
		'season': 'spring',
		'video_iframe': '<iframe width="1050" height="591" src="https://www.youtube.com/embed/Q2uoJJT2XZc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'pbl',
	},
]
