var publications_kor = [
    {   'title': '데이터 기반 심층강화학습을 통한 모션 생성',
        'representative_img':'assets/publications/domestic/2022-kcgs-DataDrivenDRL.png',
        'year': 2022,
        'authors': '박근태, 이윤상',
        'conference_journal_full': '한국컴퓨터그래픽스학회 2022년 학술대회 논문집, 34-35, 2022.07.',
        'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2022-kcgs-DataDrivenDRL.pdf">[article]</a>',
        'type': 'extended_abstract',
    },
    {   'title': '심층 강화 학습과 모션 매칭을 이용한 캐릭터 애니메이션 생성',
        'representative_img':'assets/publications/domestic/2022-kcgs-drlMotionMatching.png',
        'year': 2022,
        'authors': '이정민, 권태수, 이윤상',
        'conference_journal_full': '한국컴퓨터그래픽스학회 2022년 학술대회 논문집, 65-66, 2022.07.',
        'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2022-kcgs-drlMotionMatching.pdf">[article]</a>',
        'type': 'extended_abstract',
    },
    {   'title': '모션 매칭을 활용한 상호작용적 캐릭터 경로 추적',
        'representative_img':'assets/publications/domestic/2022-kcgs-interactivePathFollowing.png',
        'year': 2022,
        'authors': '이정민, 권태수, 이윤상',
        'conference_journal_full': '한국컴퓨터그래픽스학회 2022년 학술대회 논문집, 36-37, 2022.07.',
        'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2022-kcgs-interactivePathFollowing.pdf">[article]</a>',
        'type': 'extended_abstract',
    },
	{
		'title': 'Character Animation Basics',
		'representative_img': 'assets/publications/domestic/2022-kcgs-summerschool-character_animation_basics.png',
		'year': 2022,
		'authors': '이윤상',
		'conference_journal_full': '한국컴퓨터그래픽스학회 2022년 학술대회 여름학교, 2022.07.',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2022-kcgs-summerschool-character_animation_basics-public.pdf">[slides]</a>',
		'type': 'talk',
	},
    {
        'title':'상태 표현 방식에 따른 심층 강화 학습 기반 캐릭터 제어기의 학습 성능 비교',
        'representative_img':'assets/publications/domestic/2021-kcgsjournal-state-representation.png',
        'year':2021,
        'authors': '손채준, 권태수, 이윤상',
        'conference_journal_full':'한국컴퓨터그래픽스학회 논문지, 제 27권 제 4호, 55-61, 2021.11.',
        'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2021-kcgs-state-representation-paper.pdf">[article]</a>',
        'type': 'paper',
    },
    {
        'title':'상태 표현 방식에 따른 심층 강화 학습 기반 캐릭터 제어기의 학습 성능 비교',
        'representative_img':'assets/publications/domestic/2021-kcgsjournal-state-representation.png',
        'year':2021,
        'authors': '손채준, 이윤상',
        'conference_journal_full':'한국컴퓨터그래픽스학회 2021년 학술대회 논문집, 52-56, 2021.07.',
        'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2021-kcgs-state-representation.pdf">[article]</a>',
        'type': 'extended_abstract',
    },
    {
        'title':'2D 이동 경로 지정을 통한 모션 매칭 기반 캐릭터 모션 생성',
        'representative_img':'assets/publications/domestic/2021-kcgsjournal-2dtraj.png',
        'year':2021,
        'authors': '이정민, 이윤상',
        'conference_journal_full':'한국컴퓨터그래픽스학회 2021년 학술대회 논문집, 68-69, 2021.07.',
        'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2021-kcgs-2d-traj.pdf">[article]</a>',
        'type': 'extended_abstract',
    },
    {
        'title':'심층 강화 학습을 이용한 Luxo 캐릭터의 제어',
        'representative_img':'assets/publications/domestic/2020-journalkcgs-luxo.png',
        'year':2020,
        'authors': '이정민, 이윤상',
        'conference_journal_full':'컴퓨터그래픽스학회논문지, 제26권 제4호, 1-8, 2020.09.',
        'additional':'<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2020-kcgsjournal-luxo.pdf">[article]</a>',
        'type':'paper',
    },
	{
		'title': '무게중심을 활용한 모션 생성 기술',
		'representative_img': 'assets/publications/domestic/2020-kcgsjournal-motion-com.png',
		'year': 2020,
		'authors': '박근태, 손채준, 이윤상',
		'conference_journal_full': '한국컴퓨터그래픽스학회 논문지, 제 26권 제 2호, 11-19, 2020.06.',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2020-kcgsjournal-motion-com.pdf">[article]</a>',
		'type': 'paper',
	},
	{
		'title': '심층강화학습을 이용한 유한 상태 기반 보행 제어기의 학습',
		'representative_img': 'assets/publications/domestic/2019-kcgs-learning-fsm.png',
		'year': 2019,
		'authors': '강규철, 권태수, 이윤상',
		'conference_journal_full': '한국컴퓨터그래픽스학회 2019년 학술대회 논문집, 26-27, 2019.07.',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2019-kcgs-learning-fsm.pdf">[article]</a>',
		'type': 'extended_abstract',
	},
	{
		'title': '보행 시뮬레이션을 위한 물리의 기초',
		'representative_img': 'assets/publications/domestic/2019-orthopaedic-walking-basic.png',
		'year': 2019,
		'authors': '이윤상',
		'conference_journal_full': 'Proceeding of 2019 SNU Orthopaedic Update(II): Pediatric Orthopaedics, 115-122, 2019.06.',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2019-orthopaedic-walking-basic-slides.pdf">[slides]</a>'+
					' <a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2019-orthopaedic-walking-basic.pdf">[article]</a>',
		'type': 'talk',
	},
	{
		'title': '데이터 기반 보행 제어를 위한 다리 간 충돌 회피 기법',
		'representative_img': 'assets/publications/domestic/2017-kcgsjournal-inter-leg.png',
		'year': 2017,
		'authors': '이윤상',
		'conference_journal_full': '컴퓨터그래픽스학회논문지, 제23권 제2호, 23-27, 2017.06.',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2017-kcgsjournal-inter-leg.pdf">[article]</a>',
		'type': 'paper',
	},
	{
		'title': 'Make It Walk!: Locomotion Control',
		'representative_img': 'assets/publications/domestic/2016-kcgs-make-it-walk.png',
		'year': 2016,
		'authors': '이윤상',
		'conference_journal_full': '한국컴퓨터그래픽스학회 2016년 학술대회 초청강연, 2016.07.',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2016-kcgs-make-it-walk.pdf">[slides]</a>',
		'type': 'talk',
	},

]
