var publications_eng = [
	{
		'title': 'Utilizing Motion Matching with Deep Reinforcement Learning for Target Location Tasks',
		'authors': 'Jeongmin Lee, Taesoo Kwon, Hyunju Shin, Yoonsang Lee',
		'conference_journal': 'Eurographics',
		'year': 2024,
		'conference_journal_full': 'Eurographics 2024 Short Papers (to be appeared)',
		'representative_img': 'assets/publications/2024-matching-drl/thumb-matching-drl.png',
		'video_iframe': '<iframe width="1169" height="658" src="https://www.youtube.com/embed/kR47MrPhJGk" title="Utilizing Motion Matching with Deep Reinforcement Learning for Target Location Tasks" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
		//'project_page': 'http://calab.hanyang.ac.kr/papers/adaptiveSRB.html',
		'type': 'paper',
        //'additional': '<a href="https://dl.acm.org/doi/10.1145/3610548.3618187" rel="noopener noreferrer" target="_blank">[publisher link]</a> <a href="https://arxiv.org/abs/2308.07491" rel="noopener noreferrer" target="_blank">[arXiv]</a> <a href="https://youtu.be/oY_6dgF9P7k" rel="noopener noreferrer" target="_blank">[video]</a> <a href="https://github.com/taesoobear/IPCDNNwalk" rel="noopener noreferrer" target="_blank">[code]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2023-adaptive-tracking/adaptive-v3.pdf" rel="noopener noreferrer" target="_blank">[slides-pdf]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2023-adaptive-tracking/adaptive-v3.pptx" rel="noopener noreferrer" target="_blank">[slides-pptx]</a>',
        'additional': '<a href="https://arxiv.org/abs/2403.15902" rel="noopener noreferrer" target="_blank">[arXiv]</a> <a href="https://youtu.be/kR47MrPhJGk" rel="noopener noreferrer" target="_blank">[video]</a>',
	},
	{
		'title': 'Adaptive Tracking of a Single-Rigid-Body Character in Various Environments',
		'authors': 'Taesoo Kwon, Taehong Gu, Jaewon Ahn, Yoonsang Lee',
		'conference_journal': 'SIGGRAPH Asia',
		'year': 2023,
		'conference_journal_full': 'SA \'23: SIGGRAPH Asia 2023 Conference Papers, Article No.: 118, December 2023',
		'representative_img': 'assets/publications/2023-adaptive-tracking/thumb-adaptive-tracking.jpg',
		'video_iframe': '<iframe width="560" height="315" src="https://www.youtube.com/embed/oY_6dgF9P7k" title="Adaptive Tracking of a Single-Rigid-Body Character in Various Environments" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
		'project_page': 'http://calab.hanyang.ac.kr/papers/adaptiveSRB.html',
		'type': 'paper',
        'additional': '<a href="https://dl.acm.org/doi/10.1145/3610548.3618187" rel="noopener noreferrer" target="_blank">[publisher link]</a> <a href="https://arxiv.org/abs/2308.07491" rel="noopener noreferrer" target="_blank">[arXiv]</a> <a href="https://youtu.be/oY_6dgF9P7k" rel="noopener noreferrer" target="_blank">[video]</a> <a href="https://github.com/taesoobear/IPCDNNwalk" rel="noopener noreferrer" target="_blank">[code]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2023-adaptive-tracking/adaptive-v3.pdf" rel="noopener noreferrer" target="_blank">[slides-pdf]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2023-adaptive-tracking/adaptive-v3.pptx" rel="noopener noreferrer" target="_blank">[slides-pptx]</a>',
	},
	{
		'title': 'Learning Human-like Locomotion Based on Biological Actuation and Rewards',
		'authors': 'Minkwan Kim, Yoonsang Lee',
		'conference_journal': 'SIGGRAPH',
		'year': 2023,
		'conference_journal_full': 'SIGGRAPH \'23: ACM SIGGRAPH 2023 Posters, Article No.: 5, July 2023',
		'representative_img': 'assets/publications/2023-learning-human-like/rep-human-like.jpg',
		'video_iframe': '<iframe width="1536" height="864" src="https://www.youtube.com/embed/QPGUvpJm_Hk" title="Learning Human-like Locomotion Based on Biological Actuation and Rewards" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
		'project_page': 'publications/2023-learning-human-like.html',
		'type': 'poster',
        'additional': '<a href="https://dl.acm.org/doi/abs/10.1145/3588028.3603646" rel="noopener noreferrer" target="_blank">[publisher link]</a> <a href="http://arxiv.org/abs/2401.15664" rel="noopener noreferrer" target="_blank">[arXiv]</a> <a href="https://youtu.be/QPGUvpJm_Hk" rel="noopener noreferrer" target="_blank">[video]</a> <a href="https://dl.acm.org/action/downloadSupplement?doi=10.1145%2F3588028.3603646&file=poster-v2.pdf" rel="noopener noreferrer" target="_blank">[poster]</a>',
	},
	{
		'title': 'Interactive Character Path-Following Using Long-Horizon Motion Matching With Revised Future Queries',
		'representative_img': 'assets/publications/2023-path-following/representative.png',
		'year': 2023,
		'authors': 'Jeongmin Lee, Taesoo Kwon, Yoonsang Lee',
		'conference_journal_full': 'IEEE Access, Volume 11, 9942-9956, January 2023',
		'video_iframe': '<iframe width="1536" height="864" src="https://www.youtube.com/embed/N357UBDALpw" title="Interactive Character Path-Following using Long-Horizon Motion Matching with Revised Future Queries" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
		'project_page': 'publications/2023-path-following.html',
		'type': 'paper',
        'additional': '<a href="https://ieeexplore.ieee.org/document/10029373" rel="noopener noreferrer" target="_blank">[publisher link]</a> <a href="https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10029373" rel="noopener noreferrer" target="_blank">[paper]</a> <a href="https://youtu.be/N357UBDALpw" rel="noopener noreferrer" target="_blank">[video]</a>',
	},
	{
		'title': 'Understanding the Stability of Deep Control Policies for Biped Locomotion ',
		'representative_img': 'assets/publications/2022-stability-drl/teaser_small.jpg',
		'year': 2022,
		'authors': 'Hwangpil Park, Ri Yu, Yoonsang Lee, Kyungho Lee, Jehee Lee',
		'conference_journal_full': 'The Visual Computer, Volume 39, 473-487, January 2022',
		'project_page': 'https://mrl.snu.ac.kr/research/ProjectDeepStability/deepstability.htm',
		'type': 'paper',
        'additional': '<a href="https://link.springer.com/article/10.1007/s00371-021-02342-9" rel="noopener noreferrer" target="_blank">[publisher link]</a> <a href="https://arxiv.org/abs/2007.15242" rel="noopener noreferrer" target="_blank">[arXiv]</a> <a href="https://github.com/snumrl/DeepPushRecovery" rel="noopener noreferrer" target="_blank">[code]</a>',
	},
	{
		'title': 'Learning Time-series Interaction Data by Association',
		'representative_img': 'assets/publications/domestic/2021-ICEIC-learning-tsid.png',
		'year': 2021,
		'authors': 'GeunTae Park, Yoonsang Lee',
		'conference_journal_full': '2021 International Conference on Electronics, Information, and Communication (ICEIC), February 2021',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2021-iceic-learning-tsid.pdf" rel="noopener noreferrer" target="_blank">[article]</a>',
		'type': 'extended_abstract',
	},
	{
		'title': 'Finite State Machine-Based Motion-Free Learning of Biped Walking',
		'representative_img': 'assets/publications/2021-fsm-learning/fsm-learning.jpg',
		'year': 2021,
		'authors': 'Gyoo-Chul Kang, Yoonsang Lee',
		'conference_journal_full': 'IEEE Access, Volume 9, 20662-20672, January 2021',
		'video_iframe': '<iframe width="1047" height="589" src="https://www.youtube.com/embed/jqgf-sHqCz0" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'project_page': 'publications/2021-fsm-learning.html',
		'type': 'paper',
        'additional': '<a href="https://ieeexplore.ieee.org/document/9337805" rel="noopener noreferrer" target="_blank">[publisher link]</a> <a href="https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9337805" rel="noopener noreferrer" target="_blank">[paper]</a> <a href="https://youtu.be/jqgf-sHqCz0" rel="noopener noreferrer" target="_blank">[video]</a>',
	},
	{
		'title': 'Fast and Flexible Multilegged Locomotion Using Learned Centroidal Dynamics',
		'representative_img': 'assets/publications/2020-fast-flexible/2020-fast-flexible.jpg',
		'conference_journal': 'SIGGRAPH',
		'year': 2020,
		'authors': 'Taesoo Kwon, Yoonsang Lee, Michiel van de Panne',
		'conference_journal_full': 'ACM Transactions on Graphics (SIGGRAPH 2020), Volume 39 Issue 4, Article No. 46, July 2020',
		'video_iframe': '<iframe width="1280" height="749" src="https://www.youtube.com/embed/fGwMrRoC5bw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'project_page': 'http://calab.hanyang.ac.kr/papers/flexLoco.html',
		'type': 'paper',
        'additional': '<a href="https://dl.acm.org/doi/abs/10.1145/3386569.3392432" rel="noopener noreferrer" target="_blank">[publisher link]</a> <a href="http://calab.hanyang.ac.kr/papers/paper_flexLoco.pdf" rel="noopener noreferrer" target="_blank">[preprint]</a> <a href="https://youtu.be/fGwMrRoC5bw" rel="noopener noreferrer" target="_blank">[video]</a> <a href="https://github.com/taesoobear/IPCDNNwalk" rel="noopener noreferrer" target="_blank">[code]</a>',
	},
	{
		'title': 'Control of an Iguana Character Using Soft-Body Simulation',
		'representative_img': 'assets/publications/2018-iguana-ctrl/2018-iguana-ctrl.jpg',
		'project_page': 'publications/2018-iguana-ctrl.html',
		'year': 2018,
		'authors': 'Taesoo Kwon, Hoimin Kim, Yoonsang Lee',
		'conference_journal_full': 'IEEE Access, Volume 6, 77931-77939, December 2018',
		'video_iframe': '<iframe width="1280" height="720" src="https://www.youtube.com/embed/c37VEexDZaY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'paper',
        'additional': '<a href="https://ieeexplore.ieee.org/document/8555550" rel="noopener noreferrer" target="_blank">[publisher link]</a> <a href="https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8555550" rel="noopener noreferrer" target="_blank">[paper]</a> <a href="https://youtu.be/c37VEexDZaY" rel="noopener noreferrer" target="_blank">[video]</a>',
	},
	{
		'title': 'Performance-Based Biped Control using a Consumer Depth Camera',
		'representative_img': 'assets/publications/2017-perf-based/2017-perf-based.png',
		'project_page': 'publications/2017-perf-based.html',
		'conference_journal': 'Eurographics',
		'year': 2017,
		'authors': 'Yoonsang Lee, Taesoo Kwon',
		'conference_journal_full': 'Computer Graphics Forum (Eurographics 2017), Volume 36 Issue 2, 387-395, May 2017',
		'video_iframe': '<iframe width="1280" height="720" src="https://www.youtube.com/embed/WVDPXdlnhBM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'paper',
        'additional': '<a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/cgf.13134" rel="noopener noreferrer" target="_blank">[publisher link]</a> <a href="https://arxiv.org/abs/2401.15523" rel="noopener noreferrer" target="_blank">[arXiv]</a> <a href="https://youtu.be/WVDPXdlnhBM" rel="noopener noreferrer" target="_blank">[video]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2017-perf-based/perf-biped-v2-public.pdf" rel="noopener noreferrer" target="_blank">[slides-pdf]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2017-perf-based/perf-biped-v2-public.pptx" rel="noopener noreferrer" target="_blank">[slides-pptx]</a>',
	},
	{
		'title': 'Push-Recovery Stability of Biped Locomotion',
		'representative_img': 'assets/publications/2015-push-recovery/2015-push-recovery.png',
		'project_page': 'publications/2015-push-recovery.html',
		'conference_journal': 'SIGGRAPH Asia',
		'year': 2015,
		'authors': 'Yoonsang Lee, Kyungho Lee, Soon-Sun Kwon, Jiwon Jeong, Carol O\'Sullivan, Moon Seok Park, Jehee Lee',
		'conference_journal_full': 'ACM Transactions on Graphics (SIGGRAPH Asia 2015), Volume 34 Issue 6, Article No. 180, November 2015',
		'video_iframe': '<iframe width="1280" height="720" src="https://www.youtube.com/embed/KrTDh5Zhlac" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'paper',
        'additional': '<a href="https://dl.acm.org/doi/10.1145/2816795.2818124" rel="noopener noreferrer" target="_blank">[publisher link]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2015-push-recovery/push-recovery.pdf" rel="noopener noreferrer" target="_blank">[preprint]</a> <a href="https://youtu.be/KrTDh5Zhlac" rel="noopener noreferrer" target="_blank">[video]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2015-push-recovery/push-recovery-slides.pdf" rel="noopener noreferrer" target="_blank">[slides-pdf]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2015-push-recovery/push-recovery-slides.pptx" rel="noopener noreferrer" target="_blank">[slides-pptx]</a>',
	},
	{
		'title': 'Locomotion Control for Many-Muscle Humanoids',
		'representative_img': 'assets/publications/2014-many-muscle/2014-many-muscle.png',
		'project_page': 'publications/2014-many-muscle.html',
		'conference_journal': 'SIGGRAPH Asia',
		'year': 2014,
		'authors': 'Yoonsang Lee, Moon Seok Park, Taesoo Kwon, Jehee Lee',
		'conference_journal_full': 'ACM Transactions on Graphics (SIGGRAPH Asia 2014), Volume 33 Issue 6, Article No. 218, November 2014',
		'video_iframe': '<iframe width="1280" height="720" src="https://www.youtube.com/embed/O0zxRbZ_kNM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'paper',
        'additional': '<a href="https://dl.acm.org/doi/10.1145/2661229.2661233" rel="noopener noreferrer" target="_blank">[publisher link]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2014-many-muscle/many-muscle.pdf" rel="noopener noreferrer" target="_blank">[preprint]</a> <a href="https://youtu.be/O0zxRbZ_kNM" rel="noopener noreferrer" target="_blank">[video]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2014-many-muscle/many-muscle-slides.pdf" rel="noopener noreferrer" target="_blank">[slides-pdf]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2014-many-muscle/many-muscle-slides.pptx" rel="noopener noreferrer" target="_blank">[slides-pptx]</a>',
	},
	{
		'title': 'Data-Driven Biped Control',
		'representative_img': 'assets/publications/2010-data-driven/2010-data-driven.jpg',
		'project_page': 'publications/2010-data-driven.html',
		'conference_journal': 'SIGGRAPH',
		'year': 2010,
		'authors': 'Yoonsang Lee, Sungeun Kim, Jehee Lee',
		'conference_journal_full': 'ACM Transactions on Graphics (SIGGRAPH 2010), Volume 29 Issue 4, Article No. 129, July 2010',
		'video_iframe': '<iframe width="1017" height="765" src="https://www.youtube.com/embed/hpeqxc_1vwo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'paper',
        'additional': '<a href="https://dl.acm.org/doi/10.1145/1778765.1781155" rel="noopener noreferrer" target="_blank">[publisher link]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2010-data-driven/DataDrivenBipedControl_2010.pdf" rel="noopener noreferrer" target="_blank">[preprint]</a> <a href="https://youtu.be/hpeqxc_1vwo" rel="noopener noreferrer" target="_blank">[video]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2010-data-driven/ddbc-slides.pdf" rel="noopener noreferrer" target="_blank">[slides-pdf]</a> <a href="https://gitcgr.hanyang.ac.kr/publications/2010-data-driven/ddbc-slides-with-video.zip" rel="noopener noreferrer" target="_blank">[slides-pptx]</a>',
	},
]
